version: "3"
services:
  db:
    image: mysql:8.0
    ports:
      - 3307:3307
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password_123
      - MYSQL_DATABASE=db_kora
      - MYSQL_USER=kora
      - MYSQL_PASSWORD=test_password_123
      - MYSQL_TCP_PORT=3307
